#!/bin/bash
cd $(dirname "$0")
cp FE8_clean.gba TeleshackII.gba
wine Tools/C2EA/c2ea.exe FE8_clean.gba -installer Tables/TableInstaller.event 1> /dev/null 2> /dev/null 
./Tools/TextProcess/TextProcess Text/text_buildfile.txt Text/InstallTextData.event --narrow-mapping Text/narrow_mapping.csv --portraits Graphics/Portraits/PortraitInstaller.event 
cd ./Maps
python3 ../Tools/tmx2ea-master/tmx2ea.py -s MasterMapInstaller.event
cd ..
EventAssembler/ColorzCore A FE8 -output:TeleshackII.gba -input:ROMBuildfile.event
python3 Tools/MacOS/ups make FE8_clean.gba TeleshackII.gba TeleshackII.ups
